source 'https://rubygems.org'

ruby '2.6.3'

gem 'httparty'
gem 'thin'
gem 'squib'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'json'

group :development do
  gem 'guard'
  gem 'guard-rake'
  gem 'guard-shotgun'
end
