group :card do
  guard 'rake', task: :marvel_champions do
    watch %r{lib/marvel_champions/*}
    watch %r{img/.*}
    watch %r{.*\.yml}
  end
end

group :server do
  guard :shotgun, :server => 'thin' do
    watch %r{lib/*}
    watch %r{app/*}
  end
end
